spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/halo
    username: root
    password: openmysql
  sql:
    init:
      schema-locations:
        - classpath:schema-mysql.sql
        - classpath:schema-mysql-outbox.sql
      mode: always
      platform: mysql