spring:
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3306/halo
    username: root
    password: mariadb
  sql:
    init:
      schema-locations:
        - classpath:schema-mariadb.sql
        - classpath:schema-mariadb-outbox.sql
      mode: always
      platform: mariadb