spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/halo
    username: postgres
    password: openpostgresql
  sql:
    init:
      schema-locations:
        - classpath:schema-postgresql.sql
        - classpath:schema-postgresql-outbox.sql
      mode: always
      platform: postgresql
